#!/usr/bin/bash

for conf_dir in $HOME/.config /etc; do
    if [[ -r ${conf_dir}/gitlab-ssh.conf ]]; then
        source ${conf_dir}/gitlab-ssh.conf
        break
    fi
done

DIR_NAME=$(readlink -f $(dirname $0))

/usr/bin/ssh -p ${GITLAB_PORT:-2222} -o StrictHostKeyChecking=no ${GITLAB_HOST:-git@localhost} \
    /opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check $@ | \
    sed "s:/opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell:${DIR_NAME}/gitlab-shell-proxy:"
