#!/usr/bin/bash

for conf_dir in $HOME/.config /etc; do
    if [[ -r ${conf_dir}/gitlab-ssh.conf ]]; then
        source ${conf_dir}/gitlab-ssh.conf
        break
    fi
done

/usr/bin/ssh -p ${GITLAB_PORT:-2222} -o StrictHostKeyChecking=no ${GITLAB_HOST:-git@localhost} \
    "SSH_ORIGINAL_COMMAND=\"${SSH_ORIGINAL_COMMAND}\" \
    /opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell $@"
