#!/usr/bin/sh

for etc_dir in /etc /usr/local/etc; do
    test -r ${etc_dir}/gitlab-ssh.conf && \
        source ${etc_dir}/gitlab-ssh.conf
done

/usr/bin/ssh -p ${GITLAB_PORT:-2222} -o StrictHostKeyChecking=no ${GITLAB_URL:-git@localhost} \
    "SSH_ORIGINAL_COMMAND=\"${SSH_ORIGINAL_COMMAND}\" \
    /opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell $@"
